easy_admin:
    site_name: "Chach'Admin"

    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            # - '@VichUploader/Form/fields.html.twig'
        menu:
            - { entity: 'Actu', label: "Page d'accueil (Actu)" }
            - { entity: 'LeChef', label: "Biographie ('Le Chef')" }
            - { entity: 'Menu', label: 'Menus' }
            - { label: 'Calendrier', route: 'booking_calendar' }

    entities:
#        # List the entity class name you want to manage
        Menu:
            class: App\Entity\Menu
            list:
                fields:
                    - online
                    - type
                    - titre
                    - { property: 'image', type: 'image', base_path: 'build%app.path.menu_images%' }
                    - introduction
                    - entree
                    - d_entree
                    - plat
                    - d_plat
                    - dessert
                    - d_dessert
                    - prix
                    - updatedAt
                    
            show:
                fields:
                    - online
                    - type
                    - titre
                    - { property: 'image', type: 'image', base_path: 'build%app.path.menu_images%' }
                    - introduction
                    - entree
                    - d_entree
                    - plat
                    - d_plat
                    - dessert
                    - d_dessert
                    - prix
                    - updatedAt
                    
            form:
                fields:
                    - type
                    - titre
                    - { property: 'imageFile', type: 'vich_image', base_path: 'build%app.path.menu_images%' }
                    - introduction
                    - entree
                    - d_entree
                    - plat
                    - d_plat
                    - dessert
                    - d_dessert
                    - prix
                    - online
        
        LeChef:
            class: App\Entity\LeChef
            list:
                fields:
                    - online
                    - titre
                    - description
                    - { property: 'image', type: 'image', base_path: 'build%app.path.lechef_images%' }
                    - updatedAt
                    
            show:
                fields:
                    - online
                    - titre
                    - description
                    - { property: 'image', type: 'image', base_path: 'build%app.path.lechef_images%' }
                    - updatedAt
                    
            form:
                fields:
                    - titre
                    - description
                    - { property: 'imageFile', type: 'vich_image', base_path: 'build%app.path.lechef_images%' }
                    - online
       
        Actu:
            class: App\Entity\Actu
            list:
                fields:
                    - online
                    - titre
                    - contenu
                    - { property: 'image', type: 'image', base_path: 'build%app.path.actu_images%' }
                    - updatedAt
                    
            show:
                fields:
                    - online
                    - titre
                    - contenu
                    - { property: 'image', type: 'image', base_path: 'build%app.path.actu_images%' }
                    - updatedAt
                    
            form:
                fields:
                    - titre
                    - contenu
                    - { property: 'imageFile', type: 'vich_image', base_path: 'build%app.path.actu_images%' }
                    - online