easy_admin:
    site_name: "Chach'Admin"
    entities:
#        # List the entity class name you want to manage
        Menu:
            class: App\Entity\Menu
            list:
                fields:
                    - type
                    - titre
                    - { property: 'image', type: 'image', base_path: '%app.path.menu_images%' }
                    - introduction
                    - entree
                    - d_entree
                    - plat
                    - d_plat
                    - dessert
                    - d_dessert
                    - prix
                    
            show:
                fields:
                    - type
                    - titre
                    - { property: 'image', type: 'image', base_path: '%app.path.menu_images%' }
                    - introduction
                    - entree
                    - d_entree
                    - plat
                    - d_plat
                    - dessert
                    - d_dessert
                    - prix
                    
            form:
                fields:
                    - type
                    - titre
                    - { property: 'imageFile', type: 'vich_image' }
                    - introduction
                    - entree
                    - d_entree
                    - plat
                    - d_plat
                    - dessert
                    - d_dessert
                    - prix
        
        LeChef:
            class: App\Entity\LeChef
            list:
                fields:
                    - titre1
                    - description1
                    - { property: 'image1', type: 'image', base_path: '%app.path.lechef_images%' }
                    - titre2
                    - description2
                    - { property: 'image2', type: 'image', base_path: '%app.path.lechef_images%' }
                    
            show:
                fields:
                    - titre1
                    - description1
                    - { property: 'image1', type: 'image', base_path: '%app.path.lechef_images%' }
                    - titre2
                    - description2
                    - { property: 'image2', type: 'image', base_path: '%app.path.lechef_images%' }
                    
            form:
                fields:
                    - titre1
                    - description1
                    - { property: 'imageFile1', type: 'vich_image' }
                    - titre2
                    - description2
                    - { property: 'imageFile2', type: 'vich_image' }
       
        Actu:
            class: App\Entity\Actu