easy_admin:
    site_name: "Chach'Admin"

    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            # - '@VichUploader/Form/fields.html.twig'

    entities:
#        # List the entity class name you want to manage
        Menu:
            class: App\Entity\Menu
            list:
                fields:
                    - type
                    - titre
                    - { property: 'image', type: 'image', base_path: 'build%app.path.menu_images%' }
                    - introduction
                    - entree
                    - d_entree
                    - plat
                    - d_plat
                    - dessert
                    - d_dessert
                    - prix
                    
            show:
                fields:
                    - type
                    - titre
                    - { property: 'image', type: 'image', base_path: 'build%app.path.menu_images%' }
                    - introduction
                    - entree
                    - d_entree
                    - plat
                    - d_plat
                    - dessert
                    - d_dessert
                    - prix
                    
            form:
                fields:
                    - type
                    - titre
                    - { property: 'imageFile', type: 'vich_image', base_path: 'build%app.path.menu_images%' }
                    - introduction
                    - entree
                    - d_entree
                    - plat
                    - d_plat
                    - dessert
                    - d_dessert
                    - prix
        
        LeChef:
            class: App\Entity\LeChef
            list:
                fields:
                    - titre
                    - description
                    - { property: 'image', type: 'image', base_path: 'build%app.path.lechef_images%' }
                    
            show:
                fields:
                    - titre
                    - description
                    - { property: 'image', type: 'image', base_path: 'build%app.path.lechef_images%' }
                    
            form:
                fields:
                    - titre
                    - description
                    - { property: 'imageFile', type: 'vich_image', base_path: 'build%app.path.lechef_images%' }
       
        Actu:
            class: App\Entity\Actu