vich_uploader:
    db_driver: orm

    mappings:
        lechef_images:
            uri_prefix: /build/images/uploads/lechef
            upload_destination: '%kernel.project_dir%/assets/%app.path.lechef_images%'
            
        menu_images:
            uri_prefix: /build/images/uploads/menu
            upload_destination: '%kernel.project_dir%/assets/%app.path.menu_images%'
