-- MySQL Script generated by MySQL Workbench
-- ven. 13 avril 2018 12:00:46 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`type_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type_menu` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menu` (
  `id` INT NOT NULL,
  `titre` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `introduction` MEDIUMTEXT NULL,
  `entree` MEDIUMTEXT NULL,
  `plat` MEDIUMTEXT NULL,
  `dessert` MEDIUMTEXT NULL,
  `prix` INT NULL,
  `Fk_type_menu_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_type_menu_id_idx` (`Fk_type_menu_id` ASC),
  CONSTRAINT `fk_type_menu_id`
    FOREIGN KEY (`Fk_type_menu_id`)
    REFERENCES `mydb`.`type_menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `tel` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `Fk_menu_id` INT NULL,
  `Fk_client_id` INT NOT NULL,
  `convives` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menu_titre_idx` (`Fk_menu_id` ASC),
  INDEX `fk_client_id_idx` (`Fk_client_id` ASC),
  CONSTRAINT `fk_menu_titre`
    FOREIGN KEY (`Fk_menu_id`)
    REFERENCES `mydb`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_id`
    FOREIGN KEY (`Fk_client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actu` (
  `id` INT NOT NULL,
  `titre` VARCHAR(45) NULL,
  `contenu` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
