accueil:
    path: /
    controller: App\Controller\AccueilController::index


contact:
    path: /contact
    controller: App\Controller\ContactController::index


lechef:
    path: /lechef
    controller: App\Controller\LeChefController::index

menu:
    path: /menu
    controller: App\Controller\MenuController::index
